apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: log-output-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /log-output
        pathType: Prefix
        backend:
          service:
            name: log-output-svc
            port:
              number: 80