apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
spec:
  type: ClusterIP  # ClusterIP porque vamos usar Ingress
  selector:
    app: log-output
  ports:
    - port: 80
      targetPort: 3000